//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Powerlink
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        public int ID { get; set; }
        public string Eqp_Name { get; set; }
        public string Eqp_Category { get; set; }
        public Nullable<int> Eqp_Price { get; set; }
        public Nullable<int> Eqp_Quantity { get; set; }
        public string Eqp_Description { get; set; }
    }
}
